version: '3.4'

services:
  awstesting:
    image: awstesting
    container_name: awstesting
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    volumes:
    - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: AwsTesting/Dockerfile
    networks:
      - brent
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - DEBUG=1
      - SERVICES=cloudwatch,s3,secretsmanager,lambda,sqs,sns
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/localsetup.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - brent
networks:
  brent:
    driver: bridge 